### ISSUE TITLE
FANUC Compatibility Question

### ISSUE THREAD

**Issue by rastreus** [onerobotics/go-fanuc#1]
Can this library be used to access a FANUC Paint Mate 200iA 5L with a R-30iB controller? What PAC codes and/or settings need to be enabled?

I am specifically tasked with sending TP programs as .LS files to the controller (the R-796 ACSII Loader PAC code is installed/enabled), starting the TP program programmatically, relaying the job's status and any alert faults to a custom user interface and then being able to pause / resume the job after resetting alert faults. It seems like a fairly basic task, but I am new to the world of enterprise robotics.

The R-641 PC Interface PAC code is also installed/enabled as this task is planned to use the FANUC PCDK, but it would be better to use a simple, modern library to interact with the FANUC robot and not create an unnecessary dependency on Windows and the .NET Framework with the PCDK's ActiveX COM objects.

I guess I didn't realize that the controller could be accessed through HTTP requests. Do you have (or can point me in the right direction) the documentation for the controller's available HTTP endpoints?

**Comment by unreal** [comment]
This package should work with any FANUC robot R-30iA and newer... any robot that has the built-in webserver.

That being said, FANUC robots don't provide an HTTP API in the traditional sense. A number of things can be retrieved from the robot webserver, but they are not provided in an easy-to-use format e.g. JSON or XML. This library uses regular expressions to parse some of this stuff into something more usable. It is definitely _read-only_ at this point, but there are a few things that _could_ be written. See [comtool].

If you need to send ASCII programs to the controller, you could use FTP. The other stuff is definitely PCDK territory. You could duplicate PCDK's functionality with your own KAREL server, but it's probably not worth the effort.

[comtool]: https://github.com/onerobotics/comtool

**Comment by gavanderhoorn** [comment]
> Do you have (or can point me in the right direction) the documentation for the controller's available HTTP endpoints?

Ha, this made me smile.

> It seems like a fairly basic task, but I am new to the world of enterprise robotics.

Welcome to the world of Fanuc robots.

**Comment by gavanderhoorn** [comment]
Btw @unreal: the Fanuc RPC protocol (`tcp://:3002`) has been largely reversed. No need for the PCDK.

**Comment by rastreus** [comment]
> ... the Fanuc RPC protocol (`tcp://:3002`) has been largely reversed. No need for the PCDK.

@gavanderhoorn, does one of your libraries communicate directly to the robot controller with the reversed Fanuc RPC protocol? Any help or direction would be highly appreciated.

**Comment by gavanderhoorn** [comment]
No. Even if I had something, I would probably not publish it. I'm a big proponent and user of OSS, but there are some things that benefit from a more controlled form of distribution.
