### ISSUE TITLE
Real-time Error Monitoring?

### ISSUE THREAD

**Issue by rastreus** [onerobotics/go-fanuc#3]
@unreal @gavanderhoorn I see that this application does a lot of regex parsing. For monitoring the current errors of a FANUC robot from an external application (connected to the Robot on the same LAN) is the best thing just to regularly poll and parse the /MD/ERRACT.LS file for changes every second?

Is it possible to have a simple KAREL server running with a global ERROR[*] condition handler that catches all error conditions that occur while running a TP file as a Task and then sends socket messages about the Error (Facility code, Error code, etc.) to the external application to parse and display in real-time?

Any suggestions or tips would be really appreciated.

**Comment by gavanderhoorn** [comment]
Are you willing to pay any money (to Fanuc that is)?

---

Edit: reason I ask is because there a few official ways to do this: "error output" option (I forget which option nr it is exactly), SNPX and even just regular EtherNet/IP (possibly other fieldbus).

All of those are supported by Fanuc, people know how they work, you get to call someone if they don't work, etc.

Writing something yourself would be perfectly possible. See [this post](https://www.robot-forum.com/robotforum/thread/23247-send-active-alarm-to-plc/?postID=98820#post98820) fi (although it uses a condition handler with two registers, but it would be a similar idea).

> Is it possible to have a simple KAREL server running with a global ERROR[*] condition handler that catches all error conditions that occur while running a TP file as a Task and then sends socket messages about the Error (Facility code, Error code, etc.) to the external application to parse and display in real-time?

Yes, that would be perfectly possible. We do this in ROS actually. See [here](https://github.com/gavanderhoorn/fanuc_driver_exp/blob/03db06072787205d95a5f19b154a682f31e5dc04/src/ros_state.kl#L369-L387) and [here](https://github.com/gavanderhoorn/fanuc_driver_exp/blob/03db06072787205d95a5f19b154a682f31e5dc04/src/ros_state.kl#L446-L505). That data is streamed to the ROS side at something like 10 Hz.

**Comment by rastreus** [comment]
@gavanderhoorn It is quite possible that I already have the official PAC options and don't even realize it. The following list of options is from my `SUMMARY.DG` file.
I have access to manuals, but I'm not sure where to start? Maybe it's `Alarm Cause/Remedy R665`?

---------
Edit: I looked around a little more and see that I do not have `Error Code Output J527`. Thank you for the forum link and the ROS code examples.

```
CONFIG::
FEATURE:              ORD NO:
LR PaintTool (N. A.)  H558
English Dictionary    H521
4D Standard           R782
Analog I/O            H550
Angle Shift           J614
Auto Software Update  ATUP
Automatic Backup      J545
Background Editing    J616
Camera I/F            VCAM
Common calib UIF      CUIF
Condition Monitor     J628
Control Reliable      CNRE
Core PaintTool        PACM
Data Acquisition      R631
Diagnostic log        RSCH
Document Viewer       DOCV
Dual Check Safety UIF DCSU
Enhanced User Frame   J604
Ext. DIO Config       EIOC
Extended Error Log    R542
Extended User Frames  R696
External DI BWD       ESET
FCTN Menu Save        J516
FTP Interface         J716
Group Mask Exchange   MASK
HTTP Proxy Svr        PRXY
High-Speed Skip       J627
Host Communications   HOCO
Hour Meter            J513
I/O Interconnect 2    J542
Incr Instruction      J510
KAREL Cmd. Language   J650
KAREL Run-Time Env    J539
Kernel + Basic S/W    H510
License Checker       LCHK
LogBook(System)       OPLG
MACROs, Skip/Offset   J503
MMR Motion log        PSLG
Mate controller       MATE
MechStop Protection   MCSP
Mirror Shift          J506
Mixed logic           J554
Mode Switch           MDSW
Motion Diag. Core     MDCO
Motion Optm. Core     OPCO
Motion Profiler       MPRO
Motion Trigger        J625
Motion logger         R637
Multi-Tasking         J600
P700 J1 Backlash      BKTQ
Paint Legecy ZDT      PZDT
Position Registers    J514
Print Function        J507
Prog Num Selection    J515
Program Adjust        J517
Program Shift         J505
Program Status        PRST
Program Viewer        J697
RDM Robot Discovery   FRDM
Remote Conn Standard  RMCN
Robot Servo Code      H930
SNPX basic            SNBA
Shift Library         SHLB
Shift and Mirror Lib  SMLB
Socket Messaging      R636
System Trigger        SYTG
TCP Auto Set          J520
TCP/IP Interface      HTCP
TMILIB Interface      TMIL
TP Firmware           R789
TP Menu Accounting    TPAC
TPTX                  TPTX
Telnet Interface      TELN
Tool Offset           J509
Torque Simulator I/F  J882
Trouble Diag. & Prev. J958
Unexcepted motn Check UECK
User Frame            UFRM
VCalibration Common   VCCM
Vision Core           VCOR
Vision Library        VIPL
Vision SP CSUI        CSUI
Vision SP CSXC        CSXC
Web Plus              WEBP
Web Server            HTTP
Web Svr Enhancements  R626
iPendant              CGTP
iPendant Grid Display IGUI
iPendant Setup        IPGS
iRCalib. Standard     IRCL
Basic Positioner      H896
Paint Mate 200iA/5L   H681
4D Graphics           R764
Alarm Cause/Remedy    R665
Ascii Program Loader  R796
Ascii Upload          R507
AutoSingularityAvoidP R513
Cycle Time Priority   J523
Ethernet Sniffer      R659
FRA Params            R650
HMI Device (SNPX)     R553
Jog in Auto Mode      R694
Motion Interface      R583
NRTL                  J547
Online Help           R664
Operation logbook     J695
PC Interface          R641
PC Remote iPendant    R850
PaintTool Diagnostics R589
Parameter Control     R643
Password Protection   J541
Persistent Strg       NVDT
ROS Ethernet Packets  R603
TP Error Recovery     R642
64MB DRAM             D064
64MB FROM             F064
Auto SingularityAvoid RTSA
Aux Servo Code        SVMO
Cycle time Opt.       CTOP
Data Monitor Common   DMCM
Demo Control          R769
Email Client          JNN7
No memory card        NOMC
OPT TP Ins            OPIS
PC Send Macros        SEND
Positioner Utilities  N100
Robot Library Setup   RLCM
Servo Schedule        SVSH
```

**Comment by gavanderhoorn** [comment]
> Thank you for the forum link and the ROS code examples.

There's nothing ROS-specific about that Karel code btw.

It is used by that particular ROS driver though.

**Comment by unreal** [comment]
What @gavanderhoorn said :)

The goal of go-fanuc is to provide a semi-usable (read-only at this time) interface to FANUC robots without using any additional options or private APIs. It's certainly not real-time, but long-polling is probably ok for some applications.

**Comment by gavanderhoorn** [comment]
> The goal of go-fanuc is to provide a semi-usable (read-only at this time) interface to FANUC robots without using any additional options or private APIs. It's certainly not real-time, but long-polling is probably ok for some applications.

Bit of a plug, but [dominh](https://github.com/gavanderhoorn/dominh) has the same goals. It's just Python. And some parts are not read-only.

If someone requires determinism, they should buy one of the supported options, use a fieldbus or the PCDK.

**Comment by rastreus** [comment]
@unreal Thank you. I appreciate that `go-fanuc` is open source code. I may have to resort to a regex parsing method similar to how you are getting the errors from the /MD/ERRALL.LS file.

@gavanderhoorn Thank you for plugging [dominh](https://github.com/gavanderhoorn/dominh). I did not realize that you had started work on this RPC interface. I currently have the PCDK, but I have a requirement to target a non-Windows OS. The ActiveX COM library of the PCDK has been a limitation for me.

I just briefly looked over the README for dominh. Is it using the Fanuc RPC protocol (`tcp://:3002`) that has been reversed? If that is the case, could it have an error / alarm event handler that returns JSON with the alarm facility code and error code?

**Comment by gavanderhoorn** [comment]
>  Is it using the Fanuc RPC protocol (`tcp://:3002`) that has been reversed?

No, it doesn't.

And that's on purpose.

I have some friends to keep :wink:

**Comment by rastreus** [comment]
@gavanderhoorn I understand.

This is kind of back to my original question, but would it still be possible for a tool like `go-fanuc` or `dominh` to have some kind of error / alarm event handler like I've described without using the actual Fanuc RPC protocol? You all have a much better understanding of Fanuc KAREL than I do. It seems like having some kind of `Condition [1]: WHEN ERROR[*] DO` condition handler block would be more performant than constantly FTPing and parsing the /MD/ERRACT.LS file.

**Comment by gavanderhoorn** [comment]
Yes. That would be perfectly possible.

That's why I linked you to those posts and the Karel snippets.

You'd have to make sure the Karel prog is run continuously though.

Alternatively you could use a condition monitor. That's essentially a TP program which acts like/registers in the same way as your `CONDITION` pseudo code.
